spring:
  application:
    name: spring-boot-schedule
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ENC(Clm4vL2UAeQ3OkwA4lUWhyTys0SdYnWBtO+vCSQWwK7ArWD7r+tBM7hVvhvPgNJ/fTvOlHD103Ghj3A1M0dsg3GWhma5p9USUzxZIoGCNEv9PISiUetQKt16nmdYBJ5VbTtNJWfpCCsZtLn1yzgsx1WKBkQkzhSw0V8mgMUOOdU=)
    username: ENC(VD22GqHpdUOFDkRrosdSmg==)
    password: ENC(IJX8SKRsYnjFZ+imdUX4vw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 15
      max-lifetime: 1800000
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000

#jasypt加密的密钥
jasypt:
  encryptor:
    password: zhent1616

