
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # activiti default configuration
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
    #    process-definition-location-suffixes:
    #      - **.bpmn
    #      - **.bpmn20.xml
    history-level: full
    thymeleaf:
      enabled: true
      encoding: UTF-8
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      check-template-location: true
      servlet:
        content-type: text/html
      resources:
        static-locations: classpath:/
